name: coal
description: A suite for easily building beautiful command-line apps.
version: 0.0.2
repository: https://github.com/medz/coal

environment:
  sdk: ^3.9.2

dependencies:
  unorm_dart: ^0.3.2
  characters: ^1.4.1
  meta: ^1.17.0

dev_dependencies:
  args: ^2.7.0
  benchmark_harness: ^2.3.1
  lints: ^6.0.0
  oxy: ^0.0.4
  test: ^1.25.6
