name: coal
description: A suite for easily building beautiful command-line apps.
version: 0.0.0-dev.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  alien_signals: ^1.0.3
  unorm_dart: ^0.3.2
  characters: ^1.4.1
  meta: ^1.17.0
  platform: ^3.1.6

dev_dependencies:
  lints: ^6.0.0
  oxy: ^0.0.4
  test: ^1.25.6
