// Upstream sync metadata:
// - repository: https://github.com/spf13/cobra
// - source file: bash_completionsV2.go
// - release tag: v1.10.2
// - release date: 2025-12-04
// - tag commit: 88b30ab89da2d0d0abb153818746c5a2d30eccec
// - synced at (UTC): 2026-02-06T14:01:17Z
// Sync policy: only sync from upstream released tags (never main/dev branches).
// Reference: https://github.com/spf13/cobra/blob/v1.10.2/bash_completionsV2.go

import '../flags.dart';
import '_utils.dart';

String bashScript(String name, String exec) {
  validateShellCommandName(name);
  final escapedName = nameForVar(name);
  final execWords = shellWords(exec);
  return '''# bash completion for $name
#----------------------------------------
# This file is generated by the Coal TAB.
#----------------------------------------
# Date: ${DateTime.now()}
#----------------------------------------

# Function to debug completion
__${escapedName}_debug() {
    if [[ -n \${BASH_COMP_DEBUG_FILE:-} ]]; then
        echo "\$*" >> "\${BASH_COMP_DEBUG_FILE}"
    fi
}

# Function to handle completions
__${escapedName}_complete() {
    local cur prev words cword
    local shellCompDirectiveError=${ShellCompDirective.error}
    local shellCompDirectiveNoSpace=${ShellCompDirective.noSpace}
    local shellCompDirectiveNoFileComp=${ShellCompDirective.noFileComp}
    local shellCompDirectiveFilterFileExt=${ShellCompDirective.filterFileExt}
    local shellCompDirectiveFilterDirs=${ShellCompDirective.filterDirs}
    local shellCompDirectiveKeepOrder=${ShellCompDirective.keepOrder}

    _get_comp_words_by_ref -n "=:" cur prev words cword

    local out directive arg
    local -a requestComp

    # Build the command to get completions
    requestComp=($execWords complete --)
    for arg in "\${words[@]:1}"; do
        requestComp+=("\$arg")
    done

    # Add an empty parameter if the last parameter is complete
    if [[ -z "\$cur" ]]; then
        requestComp+=("")
    fi

    # Get completions from the program
    out=\$("\${requestComp[@]}" 2>/dev/null)

    # Extract directive if present
    directive=\${out##*:}
    out=\${out%:*}
    if [[ "\$directive" == "\$out" ]]; then
        # There is no directive specified.
        directive=0
    fi

    # Process completions based on directive
    if [[ \$((directive & shellCompDirectiveError)) -ne 0 ]]; then
        # Error, no completion
        return
    fi

    # When completing a flag with an = (e.g., --name=<TAB>)
    # bash focuses on the part after the =.
    if [[ "\$cur" == -*=* ]]; then
        cur="\${cur#*=}"
    fi

    # Apply directives
    if [[ \$((directive & shellCompDirectiveNoSpace)) -ne 0 ]]; then
        if [[ \$(type -t compopt) == builtin ]]; then
            compopt -o nospace 2>/dev/null || true
        fi
    fi
    if [[ \$((directive & shellCompDirectiveKeepOrder)) -ne 0 ]]; then
        if [[ \$(type -t compopt) == builtin ]]; then
            # no sort isn't supported for bash < 4.4
            if [[ \${BASH_VERSINFO[0]} -gt 4 ||
                ( \${BASH_VERSINFO[0]} -eq 4 && \${BASH_VERSINFO[1]} -ge 4 ) ]]; then
                compopt -o nosort 2>/dev/null || true
            fi
        fi
    fi
    if [[ \$((directive & shellCompDirectiveNoFileComp)) -ne 0 ]]; then
        if [[ \$(type -t compopt) == builtin ]]; then
            compopt +o default 2>/dev/null || true
        fi
    fi

    # Handle file extension filtering
    if [[ \$((directive & shellCompDirectiveFilterFileExt)) -ne 0 ]]; then
        local filter=""
        for ext in \$out; do
            filter="\$filter|\$ext"
        done
        filter="\\.(\$filter)"
        compopt -o filenames 2>/dev/null || true
        COMPREPLY=( \$(compgen -f -X "!\$filter" -- "\$cur") )
        return
    fi

    # Handle directory filtering
    if [[ \$((directive & shellCompDirectiveFilterDirs)) -ne 0 ]]; then
        compopt -o dirnames 2>/dev/null || true
        COMPREPLY=( \$(compgen -d -- "\$cur") )
        return
    fi

    # Process completions
    local IFS=\$'\\n'
    local tab=\$(printf '\\t')

    # Parse completions with descriptions
    local completions=()
    while read -r comp; do
        if [[ "\$comp" == *\$tab* ]]; then
            # Split completion and description
            local value=\${comp%%\$tab*}
            local desc=\${comp#*\$tab}
            completions+=("\$value")
        else
            completions+=("\$comp")
        fi
    done <<< "\$out"

    # Return completions
    COMPREPLY=( \$(compgen -W "\${completions[*]}" -- "\$cur") )
}

# Register completion function
complete -F __${escapedName}_complete $name
''';
}
