// Upstream sync metadata:
// - repository: https://github.com/spf13/cobra
// - source file: fish_completions.go
// - release tag: v1.10.2
// - release date: 2025-12-04
// - tag commit: 88b30ab89da2d0d0abb153818746c5a2d30eccec
// - synced at (UTC): 2026-02-06T14:01:17Z
// Sync policy: only sync from upstream released tags (never main/dev branches).
// Reference: https://github.com/spf13/cobra/blob/v1.10.2/fish_completions.go

import '../flags.dart';
import '_utils.dart';

String fishScript(
  String name,
  String exec, {
  bool enableDefaultCompletion = false,
}) {
  validateShellCommandName(name);
  final escapedName = nameForVar(name);
  final execWords = fishWords(exec);
  return '''# fish completion for $name -*- shell-script -*-
#----------------------------------------
# This file is generated by the Coal TAB.
#----------------------------------------
# Date: ${DateTime.now()}
#----------------------------------------

# Define shell completion directives
set -l ShellCompDirectiveError ${ShellCompDirective.error}
set -l ShellCompDirectiveNoSpace ${ShellCompDirective.noSpace}
set -l ShellCompDirectiveNoFileComp ${ShellCompDirective.noFileComp}
set -l ShellCompDirectiveFilterFileExt ${ShellCompDirective.filterFileExt}
set -l ShellCompDirectiveFilterDirs ${ShellCompDirective.filterDirs}
set -l ShellCompDirectiveKeepOrder ${ShellCompDirective.keepOrder}

function __${escapedName}_debug
    set -l file "\$BASH_COMP_DEBUG_FILE"
    if test -n "\$file"
        echo "\$argv" >> \$file
    end
end

function __${escapedName}_perform_completion
    __${escapedName}_debug "Starting __${escapedName}_perform_completion"

    # Extract all args and the current token.
    set -l args (commandline -opc)
    set -l last_arg (commandline -ct)

    __${escapedName}_debug "Args: \$args"
    __${escapedName}_debug "Last arg: \$last_arg"

    # Call the completion program and get the results
    set -l requestComp $execWords complete --
    for arg in \$args[2..-1]
        set -a requestComp "\$arg"
    end
    if test -z "\$last_arg"
        set -a requestComp ""
    else
        set -a requestComp "\$last_arg"
    end
    __${escapedName}_debug "Calling \$requestComp"
    set -l results (\$requestComp 2> /dev/null)

    # Some programs may output extra empty lines after the directive.
    # Let's ignore them or else it will break completion.
    # Ref: https://github.com/spf13/cobra/issues/1279
    for line in \$results[-1..1]
        if test (string trim -- \$line) = ""
            set results \$results[1..-2]
        else
            break
        end
    end

    # No completions, let fish handle file completions.
    if test (count \$results) -eq 0
        __${escapedName}_debug "No completions, performing file completion"
        return 1
    end

    # Parse directive line.
    set -l directive_num 0
    if test (string sub -s 1 -l 1 -- \$results[-1]) = ":"
        set -l directive (string sub -s 2 -- \$results[-1])
        if test -n "\$directive"
            set directive_num (math \$directive)
        end
        set results \$results[1..-2]
    end

    # For fish, when completing a flag with an = (e.g., --name=<TAB>)
    # completions must be prefixed with the flag.
    set -l flag_prefix (string match -r -- '-.*=' "\$last_arg")

    __${escapedName}_debug "Directive: \$directive_num"
    __${escapedName}_debug "Completions: \$results"
    __${escapedName}_debug "Flag prefix: \$flag_prefix"

    # Process completions based on directive
    if test (math "\$directive_num & \$ShellCompDirectiveError") -ne 0
        # Error code. No completion.
        __${escapedName}_debug "Received error directive: aborting."
        return 1
    end

    # No completions, let fish handle file completions unless forbidden
    if test (count \$results) -eq 0
        if test (math "\$directive_num & \$ShellCompDirectiveNoFileComp") -eq 0
            __${escapedName}_debug "No completions, performing file completion"
            return 1
        end
        __${escapedName}_debug "No completions, but file completion forbidden"
        return 0
    end

    # Fish doesn't support extension or directory filtering directives.
    if test (math "\$directive_num & \$ShellCompDirectiveFilterFileExt") -ne 0; or test (math "\$directive_num & \$ShellCompDirectiveFilterDirs") -ne 0
        __${escapedName}_debug "File extension filtering or directory filtering not supported"
        return 1
    end

    # Process remaining completions
    for item in \$results
        if test -n "\$item"
            # Check if the item has a description
            if string match -q "*\t*" -- "\$item"
                set -l completion_parts (string split --max 1 \t -- "\$item")
                set -l comp \$completion_parts[1]
                set -l desc \$completion_parts[2]

                # Add the completion and description
                echo -e "\$flag_prefix\$comp\t\$desc"
            else
                # Add just the completion
                echo -e "\$flag_prefix\$item\t"
            end
        end
    end

    # If directive contains NoSpace, tell fish not to add a space after completion
    if test (math "\$directive_num & \$ShellCompDirectiveNoSpace") -ne 0
        return 2
    end

    return 0
end

# Set up the completion for the $name command
complete -c $name -f -a "(eval __${escapedName}_perform_completion)"
''';
}
