// Upstream sync metadata:
// - repository: https://github.com/spf13/cobra
// - source file: powershell_completions.go
// - release tag: v1.10.2
// - release date: 2025-12-04
// - tag commit: 88b30ab89da2d0d0abb153818746c5a2d30eccec
// - synced at (UTC): 2026-02-06T14:01:17Z
// Sync policy: only sync from upstream released tags (never main/dev branches).
// Reference: https://github.com/spf13/cobra/blob/v1.10.2/powershell_completions.go

import '../flags.dart';
import '_utils.dart';

String powershellScript(String name, String exec) {
  validateShellCommandName(name);
  final escapedName = nameForVar(name);
  final execWords = powershellWords(exec);
  return '''# powershell completion for $name -*- shell-script -*-
#-----------------------------------------------------
# This file is generated by the Coal TAB.
#-----------------------------------------------------
# Data: ${DateTime.now()}
#-----------------------------------------------------

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    function __${escapedName}_debug {
        if (\$env:BASH_COMP_DEBUG_FILE) {
            "\$args" | Out-File -Append -FilePath "\$env:BASH_COMP_DEBUG_FILE"
        }
    }

    filter __${escapedName}_escapeStringWithSpecialChars {
        \$_ -replace '\\s|#|@|\\\$|;|,|''|\\{|\\}|\\(|\\)|"|\\||<|>|&','\\`\$&'
    }

    function __${escapedName}_commandElementValue {
        param(
            \$CommandElement,
            [int]\$CursorPosition,
            [string]\$WordToComplete
        )

        if (\$CommandElement.Extent.EndOffset -gt \$CursorPosition) {
            return \$WordToComplete
        }

        if (\$CommandElement -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            return \$CommandElement.Value
        }

        return \$CommandElement.Extent.Text
    }

[scriptblock]\$__${escapedName}CompleterBlock = {
    param(
            \$WordToComplete,
            \$CommandAst,
            \$CursorPosition
        )

    # Get the current command line.
    \$Command = \$CommandAst.Extent.Text

    __${escapedName}_debug ""
    __${escapedName}_debug "========= starting completion logic =========="
    __${escapedName}_debug "WordToComplete: \$WordToComplete Command: \$Command CursorPosition: \$CursorPosition"

    \$ShellCompDirectiveError=${ShellCompDirective.error}
    \$ShellCompDirectiveNoSpace=${ShellCompDirective.noSpace}
    \$ShellCompDirectiveNoFileComp=${ShellCompDirective.noFileComp}
    \$ShellCompDirectiveFilterFileExt=${ShellCompDirective.filterFileExt}
    \$ShellCompDirectiveFilterDirs=${ShellCompDirective.filterDirs}
    \$ShellCompDirectiveKeepOrder=${ShellCompDirective.keepOrder}

    # Prepare the command to request completions for the program.
    \$RequestComp = @($execWords, "complete", "--")

    # Use PowerShell's parser output instead of splitting on spaces, so quoted
    # arguments stay single argv values when passed to the completion backend.
    \$CommandElements = @(
        \$CommandAst.CommandElements | Where-Object { \$_.Extent.StartOffset -lt \$CursorPosition }
    )
    \$CompletionArgs = @()
    for (\$i = 1; \$i -lt \$CommandElements.Length; \$i++) {
        \$CompletionArgs += __${escapedName}_commandElementValue \$CommandElements[\$i] \$CursorPosition \$WordToComplete
    }

    if (\$CompletionArgs.Length -gt 0) {
        \$RequestComp += \$CompletionArgs
    }
    __${escapedName}_debug "RequestComp: \$RequestComp"

    # we cannot use \$WordToComplete because it
    # has the wrong values if the cursor was moved
    # so use the last argument
    if (\$CompletionArgs.Length -gt 0 -And \$WordToComplete -ne "" ) {
        \$WordToComplete = \$CompletionArgs[-1]
    }
    __${escapedName}_debug "New WordToComplete: \$WordToComplete"


    # Check for flag with equal sign
    \$IsEqualFlag = (\$WordToComplete -Like "--*=*" )
    if ( \$IsEqualFlag ) {
        __${escapedName}_debug "Completing equal sign flag"
        # Remove the flag part
        \$Flag, \$WordToComplete = \$WordToComplete.Split("=", 2)
    }

    if ( \$WordToComplete -eq "" -And ( -Not \$IsEqualFlag )) {
        # If the last parameter is complete (there is a space following it)
        # We add an extra empty parameter so we can indicate this to the go method.
        __${escapedName}_debug "Adding extra empty parameter"
        \$RequestComp += ""
    }

    __${escapedName}_debug "Calling \$RequestComp"
    # First disable ActiveHelp which is not supported for Powershell
    \$env:ActiveHelp = 0

    # call the command store the output in \$out and redirect stderr and stdout to null
    # \$Out is an array contains each line per element
    \$RequestArgs = @()
    if (\$RequestComp.Length -gt 1) {
        \$RequestArgs = \$RequestComp[1..(\$RequestComp.Length - 1)]
    }
    \$NativeArgumentPassing = Get-Variable -Name PSNativeCommandArgumentPassing -ErrorAction SilentlyContinue
    \$LegacyNativeArgs = (\$PSVersionTable.PSVersion.Major -lt 6) -or (
        \$NativeArgumentPassing -and
        \$NativeArgumentPassing.Value -eq "Legacy"
    )
    if (\$LegacyNativeArgs) {
        \$RequestArgs = @(\$RequestArgs | ForEach-Object {
            if (\$_ -eq "") { '""' } else { \$_ }
        })
    }
    \$Out = @(& \$RequestComp[0] @RequestArgs 2>\$null)
    if (\$Out.Length -eq 0) {
        return
    }

    # get directive from last line
    \$DirectiveLine = [string]\$Out[-1]
    \$DirectiveText = \$DirectiveLine.TrimStart(':')
    [int]\$Directive = 0
    if (\$DirectiveText -ne "") {
        \$Directive = [int]\$DirectiveText
    }
    __${escapedName}_debug "The completion directive is: \$Directive"

    # remove directive (last element) from out
    if (\$Out.Length -gt 1) {
        \$Out = \$Out[0..(\$Out.Length - 2)]
    } else {
        \$Out = @()
    }
    __${escapedName}_debug "The completions are: \$Out"

    if ((\$Directive -band \$ShellCompDirectiveError) -ne 0 ) {
        # Error code.  No completion.
        __${escapedName}_debug "Received error from custom completion code"
        return
    }

    \$Longest = 0
    [Array]\$Values = \$Out | ForEach-Object {
        # Split the output in name and description
        \$Name, \$Description = \$_.Split("`t", 2)
        __${escapedName}_debug "Name: \$Name Description: \$Description"

        # Look for the longest completion so that we can format things nicely
        if (\$Longest -lt \$Name.Length) {
            \$Longest = \$Name.Length
        }

        # Set the description to a one space string if there is none set.
        # This is needed because the CompletionResult does not accept an empty string as argument
        if (-Not \$Description) {
            \$Description = " "
        }
        @{ Name = "\$Name"; Description = "\$Description" }
    }


    \$Space = " "
    if ((\$Directive -band \$ShellCompDirectiveNoSpace) -ne 0 ) {
        # remove the space here
        __${escapedName}_debug "ShellCompDirectiveNoSpace is called"
        \$Space = ""
    }

    if (
        ((\$Directive -band \$ShellCompDirectiveFilterFileExt) -ne 0 ) -or
        ((\$Directive -band \$ShellCompDirectiveFilterDirs) -ne 0 )
    ) {
        __${escapedName}_debug "ShellCompDirectiveFilterFileExt ShellCompDirectiveFilterDirs are not supported"

        # return here to prevent the completion of the extensions
        return
    }

    \$Values = \$Values | Where-Object {
        # filter the result
        \$_.Name -like "\$WordToComplete*"

        # Join the flag back if we have an equal sign flag
        if ( \$IsEqualFlag ) {
            __${escapedName}_debug "Join the equal sign flag back to the completion value"
            \$_.Name = \$Flag + "=" + \$_.Name
        }
    }

    # we sort the values in ascending order by name if keep order isn't passed
    if ((\$Directive -band \$ShellCompDirectiveKeepOrder) -eq 0 ) {
        \$Values = \$Values | Sort-Object -Property Name
    }

    if ((\$Directive -band \$ShellCompDirectiveNoFileComp) -ne 0 ) {
        __${escapedName}_debug "ShellCompDirectiveNoFileComp is called"

        if (\$Values.Length -eq 0) {
            # Just print an empty string here so the
            # shell does not start to complete paths.
            # We cannot use CompletionResult here because
            # it does not accept an empty string as argument.
            ""
            return
        }
    }

    # Get the current mode
    \$Mode = (Get-PSReadLineKeyHandler | Where-Object { \$_.Key -eq "Tab" }).Function
    __${escapedName}_debug "Mode: \$Mode"

    \$Values | ForEach-Object {

        # store temporary because switch will overwrite \$_
        \$comp = \$_

        # PowerShell supports three different completion modes
        # - TabCompleteNext (default windows style - on each key press the next option is displayed)
        # - Complete (works like bash)
        # - MenuComplete (works like zsh)
        # You set the mode with Set-PSReadLineKeyHandler -Key Tab -Function <mode>

        # CompletionResult Arguments:
        # 1) CompletionText text to be used as the auto completion result
        # 2) ListItemText   text to be displayed in the suggestion list
        # 3) ResultType     type of completion result
        # 4) ToolTip        text for the tooltip with details about the object

        switch (\$Mode) {

            # bash like
            "Complete" {

                if (\$Values.Length -eq 1) {
                    __${escapedName}_debug "Only one completion left"

                    # insert space after value
                    \$CompletionText = \$(\$comp.Name | __${escapedName}_escapeStringWithSpecialChars) + \$Space
                    if (\$ExecutionContext.SessionState.LanguageMode -eq "FullLanguage"){
                        [System.Management.Automation.CompletionResult]::new(\$CompletionText, "\$(\$comp.Name)", 'ParameterValue', "\$(\$comp.Description)")
                    } else {
                        \$CompletionText
                    }

                } else {
                    # Add the proper number of spaces to align the descriptions
                    while(\$comp.Name.Length -lt \$Longest) {
                        \$comp.Name = \$comp.Name + " "
                    }

                    # Check for empty description and only add parentheses if needed
                    if (\$(\$comp.Description) -eq " " ) {
                        \$Description = ""
                    } else {
                        \$Description = "  (\$(\$comp.Description))"
                    }

                    \$CompletionText = "\$(\$comp.Name)\$Description"
                    if (\$ExecutionContext.SessionState.LanguageMode -eq "FullLanguage"){
                        [System.Management.Automation.CompletionResult]::new(\$CompletionText, "\$(\$comp.Name)\$Description", 'ParameterValue', "\$(\$comp.Description)")
                    } else {
                        \$CompletionText
                    }
                }
             }

            # zsh like
            "MenuComplete" {
                # insert space after value
                # MenuComplete will automatically show the ToolTip of
                # the highlighted value at the bottom of the suggestions.
                \$CompletionText = \$(\$comp.Name | __${escapedName}_escapeStringWithSpecialChars) + \$Space
                if (\$ExecutionContext.SessionState.LanguageMode -eq "FullLanguage"){
                    [System.Management.Automation.CompletionResult]::new(\$CompletionText, "\$(\$comp.Name)", 'ParameterValue', "\$(\$comp.Description)")
                } else {
                    \$CompletionText
                }
            }

            # TabCompleteNext and in case we get something unknown
            Default {
                # Like MenuComplete but we don't want to add a space here because
                # the user need to press space anyway to get the completion.
                # Description will not be shown because that's not possible with TabCompleteNext
                \$CompletionText = \$(\$comp.Name | __${escapedName}_escapeStringWithSpecialChars)
                if (\$ExecutionContext.SessionState.LanguageMode -eq "FullLanguage"){
                    [System.Management.Automation.CompletionResult]::new(\$CompletionText, "\$(\$comp.Name)", 'ParameterValue', "\$(\$comp.Description)")
                } else {
                    \$CompletionText
                }
            }
        }

    }
}

Register-ArgumentCompleter -CommandName '$name' -ScriptBlock \$__${escapedName}CompleterBlock
''';
}
