name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dart:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Static Analysis
        run: dart analyze

      - name: Run Tests
        run: dart test --exclude-tags=script-runtime
